export const data = [
  {
    "id": 1,
    "name": "Floral Breeze Maxi Dress",
    "brand": "Urbanic",
    "price": 2999,
    "discountPrice": 2199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Pink","White"],
    "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c",
    "description": "Elegant floral maxi dress crafted for effortless summer styling and weekend brunch outings."
  },
  {
    "id": 2,
    "name": "Velvet Evening Bodycon",
    "brand": "Forever New",
    "price": 4299,
    "discountPrice": 3299,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Black"],
    "image": "https://images.unsplash.com/photo-1483985988355-763728e1935b",
    "description": "Premium velvet bodycon dress designed for cocktail evenings and special occasions."
  },
  {
    "id": 3,
    "name": "Sunset Ruffle Midi Dress",
    "brand": "Mango",
    "price": 3499,
    "discountPrice": 2599,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Orange"],
    "image": "https://images.unsplash.com/photo-1529139574466-a303027c1d8b",
    "description": "Flowing midi dress with layered ruffles that adds movement and elegance."
  },
  {
    "id": 4,
    "name": "Ivory Co-ord Luxe Set",
    "brand": "Zara",
    "price": 4999,
    "discountPrice": 3799,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Ivory"],
    "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
    "description": "Sophisticated co-ord set tailored for modern minimalistic fashion lovers."
  },
  {
    "id": 5,
    "name": "Parisian Satin Slip Dress",
    "brand": "H&M",
    "price": 3899,
    "discountPrice": 2999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Champagne"],
    "image": "https://images.unsplash.com/photo-1509631179647-0177331693ae",
    "description": "Luxurious satin slip dress featuring a flattering silhouette and soft finish."
  },
  {
    "id": 6,
    "name": "Oversized Linen Shirt Dress",
    "brand": "Only",
    "price": 2499,
    "discountPrice": 1799,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Beige"],
    "image": "https://images.unsplash.com/photo-1495385794356-15371f348c31",
    "description": "Relaxed linen shirt dress offering breathable comfort and effortless chic."
  },
  {
    "id": 7,
    "name": "Midnight Glam Party Dress",
    "brand": "Forever 21",
    "price": 4599,
    "discountPrice": 3499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Navy Blue"],
    "image": "https://images.unsplash.com/photo-1571513722275-4b41940f54b8?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Statement-making party dress designed to turn heads at every celebration."
  },
  {
    "id": 8,
    "name": "Urban Street Crop Top",
    "brand": "Roadster",
    "price": 1499,
    "discountPrice": 999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["White"],
    "image": "https://plus.unsplash.com/premium_photo-1682095757120-c9abb908ed60?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Modern cropped top with a youthful silhouette and versatile styling options."
  },
  {
    "id": 9,
    "name": "Pleated Skater Mini Dress",
    "brand": "Urbanic",
    "price": 2799,
    "discountPrice": 1999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Lavender"],
    "image": "https://images.unsplash.com/photo-1559034750-cdab70a66b8e?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Playful skater dress with elegant pleats and a flattering fit-and-flare shape."
  },
  {
    "id": 10,
    "name": "Power Blazer Dress",
    "brand": "Zara",
    "price": 5499,
    "discountPrice": 4199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["White"],
    "image": "https://images.unsplash.com/photo-1613915617430-8ab0fd7c6baf?q=80&w=765&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Tailored blazer dress combining sharp sophistication with feminine elegance."
  },
  {
    "id": 11,
    "name": "Boho Chic Printed Maxi",
    "brand": "AND",
    "price": 3299,
    "discountPrice": 2499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Multicolor"],
    "image": "https://images.unsplash.com/photo-1564485377539-4af72d1f6a2f?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Free-spirited printed maxi dress crafted for vacations and sunny escapes."
  },
  {
    "id": 12,
    "name": "Sculpted One Shoulder Dress",
    "brand": "Mango",
    "price": 4399,
    "discountPrice": 3399,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Emerald Green"],
    "image": "https://images.unsplash.com/photo-1611042553484-d61f84d22784?q=80&w=764&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Contemporary one-shoulder silhouette tailored for premium evening styling."
  },
  {
    "id": 13,
    "name": "Blooming Floral Wrap Dress",
    "brand": "Vero Moda",
    "price": 2999,
    "discountPrice": 2299,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Yellow"],
    "image": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    "description": "Romantic wrap dress featuring floral patterns and effortless charm."
  },
  {
    "id": 14,
    "name": "Monochrome Jumpsuit",
    "brand": "Only",
    "price": 3899,
    "discountPrice": 2899,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Black"],
    "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518",
    "description": "Sleek jumpsuit with tailored lines and elevated contemporary styling."
  },
  {
    "id": 15,
    "name": "Rose Gold Sequin Dress",
    "brand": "Forever New",
    "price": 5999,
    "discountPrice": 4599,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Rose Gold"],
    "image": "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    "description": "Luxurious sequin dress crafted for glamorous nights and celebrations."
  },
  {
    "id": 16,
    "name": "Royal Embroidered Anarkali",
    "brand": "Biba",
    "price": 4999,
    "discountPrice": 3799,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Maroon"],
    "image": "https://images.unsplash.com/photo-1610030469983-98e550d6193c",
    "description": "Traditional embroidered Anarkali crafted for weddings and festive occasions."
  },
  {
    "id": 17,
    "name": "Banarasi Silk Saree",
    "brand": "W for Woman",
    "price": 6999,
    "discountPrice": 5499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Red","Gold"],
    "image": "https://images.unsplash.com/photo-1627577279497-4b24bf1021b6?q=80&w=749&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Rich Banarasi weave saree blending timeless elegance with festive grandeur."
  },
  {
    "id": 18,
    "name": "Pastel Sharara Set",
    "brand": "Libas",
    "price": 4299,
    "discountPrice": 3199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Mint Green"],
    "image": "https://plus.unsplash.com/premium_photo-1661775820832-f971657b13f6?q=80&w=1974&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Elegant pastel sharara set featuring intricate detailing and premium fabric."
  },
  {
    "id": 19,
    "name": "Chikankari Kurta Ensemble",
    "brand": "Aurelia",
    "price": 2999,
    "discountPrice": 2199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["White"],
    "image": "https://images.unsplash.com/photo-1627292441194-0280c19e74e4?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Classic chikankari kurta set delivering understated sophistication."
  },
  {
    "id": 20,
    "name": "Regal Wedding Lehenga",
    "brand": "Mohey",
    "price": 12999,
    "discountPrice": 9999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Crimson Red"],
    "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1",
    "description": "Statement bridal lehenga adorned with intricate craftsmanship and rich textures."
  },
  {
    "id": 21,
    "name": "Girls Floral Princess Dress",
    "brand": "Little Luxe",
    "price": 1499,
    "discountPrice": 1099,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Pink"],
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea",
    "description": "Charming floral dress crafted for birthday celebrations and joyful occasions."
  },
  {
    "id": 22,
    "name": "Girls Ethnic Festive Frock",
    "brand": "Tiny Trends",
    "price": 1799,
    "discountPrice": 1299,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Peach"],
    "image": "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446",
    "description": "Festive ethnic frock designed to keep little fashionistas stylish and comfortable."
  },
  {
    "id": 23,
    "name": "Emerald Satin Co-ord Set",
    "brand": "Zara",
    "price": 4499,
    "discountPrice": 3399,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Emerald Green"],
    "image": "https://images.unsplash.com/photo-1483985988355-763728e1935b",
    "description": "Premium satin co-ord set designed for effortless luxury and modern elegance."
  },
  {
    "id": 24,
    "name": "Classic Beige Trench Dress",
    "brand": "Mango",
    "price": 5299,
    "discountPrice": 3999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Beige"],
    "image": "https://images.unsplash.com/photo-1504593811423-6dd665756598",
    "description": "Sophisticated trench-inspired dress ideal for elevated city styling."
  },
  {
    "id": 25,
    "name": "Lavender Puff Sleeve Midi",
    "brand": "Forever New",
    "price": 3799,
    "discountPrice": 2899,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Lavender"],
    "image": "https://images.unsplash.com/photo-1496747611176-843222e1e57c",
    "description": "Feminine midi dress with puff sleeves and a romantic silhouette."
  },
  {
    "id": 26,
    "name": "Midnight Velvet Blazer",
    "brand": "H&M",
    "price": 4799,
    "discountPrice": 3599,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Black"],
    "image": "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
    "description": "Sharp velvet blazer crafted for power dressing and luxury styling."
  },
  {
    "id": 27,
    "name": "Sunflower Resort Maxi",
    "brand": "Only",
    "price": 3299,
    "discountPrice": 2499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Yellow"],
    "image": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    "description": "Vacation-ready maxi dress featuring vibrant summer-inspired prints."
  },
  {
    "id": 28,
    "name": "Rose Pleated Mini Skirt",
    "brand": "Urbanic",
    "price": 1999,
    "discountPrice": 1499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Rose Pink"],
    "image": "https://images.unsplash.com/photo-1487412947147-5cebf100ffc2",
    "description": "Trendy pleated mini skirt perfect for youthful street-style looks."
  },
  {
    "id": 29,
    "name": "Crystal Glam Sequin Gown",
    "brand": "Forever New",
    "price": 7499,
    "discountPrice": 5999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Silver"],
    "image": "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    "description": "Dazzling sequin gown created for luxury evening occasions."
  },
  {
    "id": 30,
    "name": "Soft Knit Winter Dress",
    "brand": "Mango",
    "price": 4199,
    "discountPrice": 3199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Cream"],
    "image": "https://plus.unsplash.com/premium_photo-1667520043080-53dcca77e2aa?q=80&w=687&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Cozy knit dress delivering warmth without compromising style."
  },
  {
    "id": 31,
    "name": "Designer Georgette Kurta Set",
    "brand": "Libas",
    "price": 3499,
    "discountPrice": 2599,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Sky Blue"],
    "image": "https://images.unsplash.com/photo-1562572159-4efc207f5aff?q=80&w=735&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Elegant georgette kurta set with intricate detailing and premium finish."
  },
  {
    "id": 32,
    "name": "Royal Zari Saree",
    "brand": "Biba",
    "price": 7999,
    "discountPrice": 6399,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Royal Blue"],
    "image": "https://images.unsplash.com/photo-1503160865267-af4660ce7bf2?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    "description": "Luxurious zari saree crafted to make every festive moment memorable."
  },
  {
    "id": 33,
    "name": "Pearl Embroidered Sharara",
    "brand": "Aurelia",
    "price": 5299,
    "discountPrice": 3999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Peach"],
    "image": "https://images.unsplash.com/photo-1603252109303-2751441dd157",
    "description": "Premium embroidered sharara set tailored for celebrations and festivities."
  },
  {
    "id": 34,
    "name": "Festive Silk Lehenga",
    "brand": "Mohey",
    "price": 10999,
    "discountPrice": 8799,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Magenta"],
    "image": "https://images.unsplash.com/photo-1594633312681-425c7b97ccd1",
    "description": "Traditional silk lehenga with luxurious craftsmanship and premium styling."
  },
  {
    "id": 35,
    "name": "Elegant Chanderi Suit",
    "brand": "W for Woman",
    "price": 3999,
    "discountPrice": 2999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Mint Green"],
    "image": "https://images.unsplash.com/photo-1610030469983-98e550d6193c",
    "description": "Lightweight Chanderi suit ideal for elegant festive celebrations."
  },
  {
    "id": 36,
    "name": "Girls Sparkle Party Gown",
    "brand": "Little Luxe",
    "price": 1999,
    "discountPrice": 1499,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Purple"],
    "image": "https://images.unsplash.com/photo-1519238263530-99bdd11df2ea",
    "description": "Sparkling party gown designed to make every celebration special."
  },
  {
    "id": 37,
    "name": "Girls Rainbow Tulle Dress",
    "brand": "Tiny Trends",
    "price": 1699,
    "discountPrice": 1199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Multicolor"],
    "image": "https://images.unsplash.com/photo-1515372039744-b8f02a3ae446",
    "description": "Fun and colorful tulle dress designed for little trendsetters."
  },
  {
    "id": 38,
    "name": "Girls Blossom Party Dress",
    "brand": "Mini Vogue",
    "price": 1899,
    "discountPrice": 1399,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Pink"],
    "image": "https://images.unsplash.com/photo-1515886657613-9f3515b0c78f",
    "description": "Beautiful floral party dress crafted for birthdays and celebrations."
  },
  {
    "id": 39,
    "name": "Girls Ethnic Lehenga Set",
    "brand": "Tiny Couture",
    "price": 2499,
    "discountPrice": 1899,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Red"],
    "image": "https://images.unsplash.com/photo-1517841905240-472988babdf9",
    "description": "Traditional lehenga set designed with comfort and festive elegance."
  },
  {
    "id": 40,
    "name": "Girls Princess Net Frock",
    "brand": "Little Luxe",
    "price": 1599,
    "discountPrice": 1199,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Lavender"],
    "image": "https://images.unsplash.com/photo-1483985988355-763728e1935b",
    "description": "Elegant net frock featuring premium detailing and soft comfort."
  },
  {
    "id": 41,
    "name": "Girls Summer Floral Dress",
    "brand": "Tiny Trends",
    "price": 1399,
    "discountPrice": 999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Yellow"],
    "image": "https://images.unsplash.com/photo-1524504388940-b1c1722653e1",
    "description": "Lightweight floral dress perfect for sunny adventures and outings."
  },
  {
    "id": 42,
    "name": "Girls Glitter Party Wear",
    "brand": "Mini Vogue",
    "price": 2299,
    "discountPrice": 1699,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Silver"],
    "image": "https://images.unsplash.com/photo-1521572267360-ee0c2909d518",
    "description": "Stylish glitter party outfit made for memorable celebrations."
  },
  {
    "id": 43,
    "name": "Girls Festive Kurti Set",
    "brand": "Tiny Couture",
    "price": 1799,
    "discountPrice": 1299,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Peach"],
    "image": "https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91",
    "description": "Comfortable festive kurti set blending tradition with modern charm."
  },
  {
    "id": 44,
    "name": "Girls Dreamy Tulle Gown",
    "brand": "Little Luxe",
    "price": 2599,
    "discountPrice": 1999,
    "sizes": ["XS","S","M","L","XL"],
    "colors": ["Sky Blue"],
    "image": "https://images.unsplash.com/photo-1509631179647-0177331693ae",
    "description": "Premium tulle gown designed for special occasions and celebrations."
  }
]